### ISSUE TITLE
Problem with redis connection

### ISSUE THREAD

**Issue by LordDeveloper** [amphp/redis#75] opened 2022-07-23 11:09 UTC
I found a problem in redis, This is my redis connection configuration:
```php
$config = config('redis');

if (isset($config['host']) && isset($config['port'])) {
    $uri = Config::fromUri('redis://' . $config['host'] . ':' . $config['port'] . '?' . http_build_query([
            'password' => $config['password'] ?? '',
            'timeout' => $config['timeout'] ?? '',
            'database' => $config['database'] ?? 0,
        ]));

    return new Redis(new RemoteExecutor($uri));
}
return null;
```
I have a infinite loop, After running each query, The redis connect and disconnect from redis server.

![image](https://user-images.githubusercontent.com/34248444/180602536-0d461d41-d8c9-4e62-9d41-a06802ece0c3.png)
https://github.com/amphp/redis/blob/90aa4f50d7889a880d15e6e4a504b398e16faa82/src/RemoteExecutor.php#L84

![image](https://user-images.githubusercontent.com/34248444/180602575-abf75617-dfae-4ef0-8592-6e8a4117e2e8.png)

**Comment by trowski** [comment] 2022-12-31 05:10
Apologies for not responding to this issue sooner. I cannot reproduce this behavior. Unfortunately without more information I'm unsure of what may have been happening.

Because some time has passed, I'm closing this issue. If you still need assistance, please open a new issue with more information.

**Closed by trowski** 2022-12-31 05:10 UTC
